-- ============================================================
-- ONE-OFF (deja execute) : rename RAW.RAW_*_AGG -> ANALYTICS.STREAM_*_AGG.
-- Ne pas re-executer. Conserve pour la tracabilite.
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE RTGAMING_DEV;

ALTER TABLE IF EXISTS RAW.RAW_PURCHASES_AGG RENAME TO ANALYTICS.STREAM_PURCHASES_AGG;
ALTER TABLE IF EXISTS RAW.RAW_REVIEWS_AGG   RENAME TO ANALYTICS.STREAM_REVIEWS_AGG;
ALTER TABLE IF EXISTS RAW.RAW_SESSIONS_AGG  RENAME TO ANALYTICS.STREAM_SESSIONS_AGG;
ALTER TABLE IF EXISTS RAW.RAW_WISHLIST_AGG  RENAME TO ANALYTICS.STREAM_WISHLIST_AGG;