apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: rtgaming
  labels:
    app: ollama
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: rtgamingdevacrmdid1l.azurecr.io/ollama/ollama:latest
          ports:
            - containerPort: 11434
              name: http
          volumeMounts:
            - name: models
              mountPath: /root/.ollama
          resources:
            requests:
              cpu: "800m"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "6Gi"
          env:
            - name: OLLAMA_NUM_PARALLEL
              value: "1"
            - name: OLLAMA_KEEP_ALIVE
              value: "24h"
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "sleep 10 && ollama pull qwen3:4b || true"
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: ollama-models