apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rtgaming-api-monitor
  namespace: rtgaming
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rtgaming-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s